### ISSUE TITLE
Poison for NPC

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#28]
Добавить движковую обработку отравления для NPC в том числе и для PM.
Сейчас это работает только для Игрока.

**Нужно обдумать... может отравление можно обрабатывать на уровне скриптов, тогда и вносить изменения в код движка не придется.**

Также можно вынести два параметра в отдельный ini файл для настройки отравления, чтобы в будущем не загромождать ddraw.ini.
```
critter_adjust_poison_(source, -2);
critter_adjust_hits_(_source, -1);
```

**Comment by Lexx2k** [comment]
Having more options is great, but not sure how tedious this gets for the player.

In any case, this would require something like new labels such as "x is poisoned" otherwise player will be confused when his party members drop dead.

Party members could use antidote on their own, too, based on current level of "chem_use" ... but I guess that must be scripted.

And if we're going the poison route, might as well consider radiation effects.

**Comment by FakelsHub** [comment]
It was planned that for NPC to make an exception and they should not die of poison.

**Comment by FakelsHub** [comment]
Требуется сделать ini файл куда нужно будет вынести настроки параметров Радиации и Отравления.

**Comment by FakelsHub** [comment]
Сделать полноценную поддержку эффекта отравления на уровне движка для криттеров нельзя, т.к. есть много противодействующих факторов.
Реализация подобия "отравления" для членов партии может быть реализована скриптовыми методами.
