### ISSUE TITLE
Проверка AI "Friendly Fire" 

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#35]
Для режима стрельбы очередью и ее оценка "friendly fire" выполняется только один раз, перед атакой,  т.к. оценка это тоже самое, что и стрельба очередью но без нанесения урона и попадание зависит от рандома, то эта оценка уже будет не верна для следующей совершенной  атаки AI.
Поэтому мы и видим частую проблему стрельбы АI по своим из-за спины.

Вариант решения проблемы:
Увеличить число попыток оценки, таким образом, если все оценки прошли успешно, то AI может безопастно применить режим стрельбы очередью.
Число попыток оценки может быть основано на значении статистики IQ криттера + некое число, которое необходимо подобрать в результате проведенных тестов.

**Comment by NovaRain** [comment]
You mean when party members use burst attack, many times they just burst anyway because the first/only check on friendly fire passed ("ok it shouldn't hit the player") but due to the randomness of burst attack, the player still got hit by one (or more) group of bullets?
I think the evaluation for burst attack should be performed at least three times because of the "three ways" pattern of the burst (middle/left/right), not sure if more attempts would help. Or maybe check for each ally between the attacker and the target if possible?

**Comment by FakelsHub** [comment]
> You mean when party members use burst attack, many times they just burst anyway because the first/only check on friendly fire passed ("ok it shouldn't hit the player") but due to the randomness of burst attack, the player still got hit by one (or more) group of bullets?

yes

> I think the evaluation for burst attack should be performed at least three times because of the "three ways" pattern of the burst (middle/left/right), not sure if more attempts would help. Or maybe check for each ally between the attacker and the target if possible?

the more attempts, the less affected by the randomizer.
no.

**Comment by FakelsHub** [comment]
В результате проведенных тестов установлено, что малое количество (10-20) попыток оценок очень незначительно влияет на результат, поэтому было решено умножить значение IQ на 16.
Но даже при таких количествах проверок, есть большая вероятность нанести урон "Friendly Fire".
_Вероятно, что сама функция `compute_spray_` как-то не очень корректно работает._

**Comment by NovaRain** [comment]
> В результате проведенных тестов установлено, что малое количество (10-20) попыток оценок очень незначительно влияет на результат, поэтому было решено умножить значение IQ на 16.
> Но даже при таких количествах проверок, есть большая вероятность нанести урон "Friendly Fire".

If _(IN * 16)_ times of the checks still couldn't prevent PC from being shot from the back more effectively, I'd think running so many checks is kinda wasted.

**Comment by FakelsHub** [comment]
I got a positive result in ~35 checks.
But 160 checks is a negligible number.

**Comment by FakelsHub** [comment]
OK I'll delete this, just make one check for the fact that there is another NPC on the line of fire.
i.e. so:
`A>--Y--T`
A: Attacker
T: Target
Y:  Third NPC
In this case, other targets located in the vicinity or behind the target will not be taken into account.

**Comment by NovaRain** [comment]
> 
> 
> OK I'll delete this, just make one check for the fact that there is another NPC on the line of fire.
> In this case, other targets located in the vicinity or behind the target will not be taken into account.

OK, this seems more reasonable IMO.

**Comment by FakelsHub** [comment]
In this case, the AI will stop using burst, even if the object Y is not will be damaged.

**Comment by NovaRain** [comment]
> 
> 
> In this case, the AI will stop using burst, even if the object Y is not will be damaged.

I suppose all the hacks for `combat_safety_invalidate_weapon_func_` so far is for preventing AI from choosing burst attack in `ai_pick_hit_mode_` (be sure/careful/absolutely sure)? Maybe add an additional check for the hit chance to the object Y to make the attacker "gamble" the chance, or a roll against attacker's IN (smarter = more careful not to hit Y)? Indeed not using burst simply because someone is between the attacker and target is a bit harsh.

**Comment by FakelsHub** [comment]
This will already be a bunch of code like with "out of range"

**Comment by NovaRain** [comment]
Oh, OK, I was hoping it'd be simpler (I guess the "stop using burst because of someone in between" is?) than the loops.

**Comment by FakelsHub** [comment]
>I guess the "stop using burst because of someone in between" is?

???

**Comment by NovaRain** [comment]
> 
> 
> > I guess the "stop using burst because of someone in between" is?
> 
> ???

I mean I thought the code for this one would be simpler:
`just make one check for the fact that there is another NPC on the line of fire.`

**Comment by FakelsHub** [comment]
I can offer an option
CheckBurstFriendlyFire = 1 check Y object
CheckBurstFriendlyFire = 2 loops check

**Comment by NovaRain** [comment]
> 
> 
> I can offer an option
> CheckBurstFriendlyFire = 1 check Y object
> CheckBurstFriendlyFire = 2 loops check

My idea was implementing a simpler/more subtle hack as the default fix, like `ai_pick_hit_mode_hook`.
But if you said AI would not use burst simply because there's another NPC on the line of fire, it seems a bit too cautious in my opinion. Of course it'd be super safe in terms of "I don't want AI use burst and accidentally hit others".
That's why I propose adding a roll against attacker's IN for some random element, for example: dice = random(1, 10); if (dice > Stat_iq), AI choose burst even if there's Y object. But this would require lots of extra coding according to your comment above.

**Comment by FakelsHub** [comment]
> That's why I propose adding a roll against attacker's IN for some random element, for example: dice = random(1, 10); if (dice > Stat_iq), AI choose burst even if there's Y object. But this would require lots of extra coding according to your comment above.

Just roll the dice it doesn't need a lot of code.
But this will not differ much from the one check of engine code in `combat_safety_invalidate_weapon_func_` because it also uses dice rolls.

**Comment by NovaRain** [comment]
> But this will not differ much from the one check of engine code in `combat_safety_invalidate_weapon_func_` because it also uses dice rolls.

I didn't see any dice roll in `combat_safety_invalidate_weapon_func_`, or you mean the one in `compute_spray_`?

**Comment by FakelsHub** [comment]
compute_spray_

**Comment by FakelsHub** [comment]
BUT I have some suspicions about the function 'tile_num_beyond_' that its algorithm still works crookedly (I did a fix for throwing weapons)
Sometimes 'compute_spray_' doesn't see some NPCs located in the line of fire.
Then the roll of the dice may be justified.

**Comment by FakelsHub** [comment]
```c++
static int32_t __fastcall RollFriendlyFire(fo::GameObject* target, fo::GameObject* attacker) {
	if (AI::CheckFriendlyFire(target, attacker)) {
		long dice = fo::func::roll_random(1, 10);
		return fo::func::stat_level(attacker, fo::STAT_iq) >= dice; // 1 - is friendly
	}
	return 0;
}
```
add this and replace of calling from `call AI::CheckFriendlyFire;` in asm code.
you will get a 40-60% chance, since most NPC have an iq stat of 4-6 units.
