### ISSUE TITLE
How to set the appearance of the elevator?

### ISSUE THREAD

**Issue by NovaRain** [FalloutTeamX/sfall-Extended#5]
I was using sfall-Ext 4.1.3 for testing. I extracted vanilla EL_BOS.FRM (with 1-4 floor buttons) from master.dat, renamed it to EL_BOSX.FRM and added at the end of RP's intrface.lst (line number 479). But when I edited RP's elevators.ini to:
```
[24] ;EPA sublevel elevator
Image=0
MainFrm=478
ButtonsFrm=-1
...
[25] ;EPA sublevel elevator
Image=0
MainFrm=478
ButtonsFrm=-1
...
```
in the game the elevators still use their old appearance (with 3-6 floor buttons). Did I miss something?

**Comment by FakelsHub** [comment]
It seems to work only for the first 23 elevators.
I will check it again...

**Comment by FakelsHub** [comment]
You change images for a 24/25 elevator, but you use Image at number 0
Must be so
```
[24]
Image=24
MainFrm=478
```
But it will not work (the game will freeze), since there are only 23 elevators
It is necessary to find the cause of the freeze of the game.

Perhaps it was necessary to use the Crafty format, it is more understandable.
```
; Only Crafty
[Frms]
Image0=143|-1
Image1=143|527
Image2=144|-1
Image3=144|145
Image4=146|-1
Image5=146|147
```

**Comment by NovaRain** [comment]
Oh, I thought the two settings were able to override the 'image' above. Crafy's settings seem only able to change the 24 vanilla elevators, guess all extra elevators still have to use vanilla ones as their template.
